### PR TITLE
Add `statascii()`

### PR DESCRIPTION
**Pull request by gvelasq2**
Changes:
1. I wrote the [`statascii()`](https://gist.github.com/gvelasq2/a39348f59f4353a9478704a28f86ed69) function (an adapted version of [`asciify()`](https://gist.github.com/gavinsimpson/2b49f3026b50eeba29314398e27a6770) by @gavinsimpson) to better approximate Stata output, including right justification, Stata-like padding, various Stata table formats (`oneway`, `twoway`, and `summary`), and Unicode box drawing characters.
2. I applied the `oneway` flavor in `statascii()` to one-way tables of frequencies in `tab()`, and I added a "Total" row.
3. I applied the `summary` flavor in `statascii()` to n-way tables of frequencies when n > 1 in `tab()`, as well as to`sum_up()`.
4. The detailed output option from `sum_up()` is too wide for Stata-like padding in the R console, so I created a unique, smaller padding for this option.
5. `pander()` is no longer necessary.

Known issues:
1. `statascii()` breaks down with wide tables that need to wrap around the R console. `pander()` has this functionality. I hope to develop a solution for this in `statascii()`.

Things to discuss:
1. @matthieugomez, what you think about `tab()` displaying a contingency table for two-way tables of frequencies? This would better approximate Stata `tabulate` output.
2. I do like the current flat table output in `tab()` for n-way tables of frequencies when n >2 (which is an improvement over Stata's `tabulate`, yet this is possible via Stata's `table`). @matthieugomez, perhaps you’d agree with adding dashed row separators to better delineate the groups when n > 2?
3. A wish list item of mine is to implement Stata `tabulate` options in a quick and easy way. Is it possible to have two `...` in a function definition in order to parse out the tab variables as well as the options? For example:

`mtcars %>% tab(gear, carb, opt = m row col exp chi2 exact)`

### CODE REVIEW

**Comment by matthieugomez** [comment]
What do you mean by "`statascii` break down"? I think you'd need to fix it before merging it.

About your questions
tab` will never be an exact equivalent of `tabulate` — it's enough for me that they fill the same goal.  I don't really think that a contingency table is that useful.
Dashed row separators may be a good idea.
It's not possible to have two `...` in a function definition.

**Comment by gvelasq2** [comment]
Thanks, @matthieugomez.

I meant that `statascii()

**Comment by gvelasq2** [comment]
@matthieugomez, I've added table wrapping functionality to `statascii()`. You can check it by running the code below.

```
mtcars %>%
    slice(1:5) %>%
    tab(mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb)
```

You'll notice that if you resize your R console and rerun the `tab()` command above, `statascii()` will automatically wrap the table output based on the current R console width.

**Comment by matthieugomez** [comment]
Thanks!

**Pull request merged**
